# Generated by Django 4.2.1 on 2023-06-14 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-date_created'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
